name: "Join Application"
description: "Application to join IT Craft Development Team (American English)"
title: "[Join Request] "
labels: ["· Join-application"]
body:
  - type: markdown
    attributes:
      value: |
        If you're interested in joining the IT Craft Development Team, please fill out the form below. Once submitted, we will process your application within 72 hours.
        Additionally, note that we might request more information from you. Thus, please keep an eye on notifications sent to your GitHub-associated email. If you don't respond to our queries within 24 hours, we'll close your application, but you can always reapply.
  - type: checkboxes
    id: agreement
    attributes:
      label: Group Agreement
      description: |
        We trust you already know what shouldn't be done. In summary, these are the 4 points:
        1. Maintain civil language and foster a positive atmosphere;
        2. Be cautious with your words, avoiding aggressive or impulsive remarks;
        3. Avoid sharing inappropriate or extreme views;
        4. Adhere to all relevant laws and regulations.
        Please confirm you have carefully read the agreement above and agree to abide by it.
      options:
        - label: I have read and agree to the terms above.
          required: true
  - type: input
    id: chat-id
    attributes:
      label: Chat platform account
      description: This is to facilitate the administrator to confirm the identity, such as the fear of privacy leakage do not fill in the can also be.
      placeholder: 
    validations:
      required: false
  - type: input
    id: age
    attributes:
      label: Your Age
      placeholder: e.g. 15
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: How did you learn about IT Craft Development Team?
      placeholder: e.g. GitHub
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why do you want to join IT Craft Development Team?
      description: Please briefly explain your reasons.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Introduce Yourself
      description: Anything else you'd like to tell us?
      placeholder: Anything goes here. If you don't have anything, that's alright. If you wish to join our Discord group, please mention your username.
    validations:
      required: false

