name: "申请加入"
description: "申请加入 IT Craft Development Team（简体中文）"
title: "[加入申请] "
labels: ["· Join-application"]
body:
  - type: markdown
    attributes:
      value: |
        如果您想加入 IT Craft Development Team，请填写下方表单。申请提交后，我们将会在 72 小时内处理。
        另请注意，我们可能会要求您提交更多信息。因此，请关注您的 GitHub 绑定邮箱通知。若您未在 24 小时内回复我们的要求，我们将关闭您的申请，不过您还可以再次提交。
  - type: checkboxes
    id: agreement
    attributes:
      label: 群规协议
      description: |
        我们相信您已经知道什么是不应该做的，总结起来无非时这 4 点：
        1. 请保持文明用语，促进良好的氛围；
        2. 请注意言辞，避免过激或冲动的发言；
        3. 请避免发表不合适和极端的观点；
        4. 请遵守现行相关法律法规。
        请确认您已仔细阅读以上协议，并且同意遵守。
      options:
        - label: 我已阅读并同意以上协议。
          required: true
  - type: input
    id: qq-id
    attributes:
      label: QQ号
      description: 您的QQ号。如果您只想加入我们的 Discord 服务器，请在「介绍一下你自己」备注。
      placeholder: e.g. 10000
    validations:
      required: true
  - type: input
    id: age
    attributes:
      label: 您的年龄
      placeholder: e.g. 15
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: 您从哪里得知 IT Craft Development Team？
      placeholder: e.g. GitHub
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: 为什么想加入 IT Craft Development Team？
      description: 请简单说明您的原因。
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: distinguish-nouns
    attributes:
      label: 区分名词
      description: |
        （非必填项，只是测试您对ITCDT的了解程度）尝试区分以下名词：
        Moonlark
        XDbot2
        XDbot
        XDbot Core
        XDbot Plus
        XDbot 0x01
        XDbot Projects
        Moonlark Projects
        Moonlark Development Team
        Moonlark Project
        XDbot2 Team
        IT Craft Studio
        IT Craft Development Team
      placeholder: |
        1. Moonlark - 慕恩拉克
        2. XDbot2 - 西迪波特贰
        3. XDbot - 西迪波特
        4. XDbot Core - 西迪波特科尔
        5. XDbot Plus - 西迪波特普拉斯
        6. XDbot 0x01 - 西迪波特零艾克斯零一
        7. XiaoDeng3386 - 萧登三三八六
        8. XDbot Projects - 西迪波特普洛杰克斯
        9. Moonlark Projects - 慕恩拉克普洛杰克斯
        10. Moonlark Development Team - 慕恩拉克迪维洛普门特提安
        11. Moonlark Project - 慕恩拉克普洛杰克
        12. XDbot2 Team - 西迪波特贰提安
        13. IT Craft Studio - 艾提克拉夫特斯图迪奥
        14. IT Craft Development Team - 艾提克拉夫特迪维洛普门特提安
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: 介绍一下你自己
      description: 你还想告诉我们什么？
      placeholder: 什么都可以哦，没有就算了吧。如果您需要加入我们的 Discord 群组，请备注您的用户名。
    validations:
      required: false

