name: "申请加入"
description: "申请加入 IT Craft Development Team（简体中文）"
title: "[加入申请] "
labels: ["join application"]
body:
  - type: markdown
    attributes:
      value: |
        如果您想加入 IT Craft Development Team，请填写下方表单。申请提交后，我们将会在 24 小时内处理
        
        另请注意，我们可能会要求您提交更多信息。因此，请关注您的 GitHub 绑定邮箱通知。若您未在 24 小时内回复我们的要求，我们将关闭您的申请，不过您还可以再次提交。
  - type: markdown
    attributes:
      value: |
        我们知道您不想阅读冗长的协议，但仍请您特别注意：
        - xxtg来写
        - 您不得帮助他人违反这些规则。
        
        对于任何违反上述协议、或是由我们判定为出现其它不合适的行为，我们将视情况终止对您的服务，并有权利公开相关的不良行为。
  - type: checkboxes
    id: preflight
    attributes:
      label: 开始之前……
      description: 让我们看看你的登机牌准备好了吗
      options:
        - label: 我同意以上协议
          required: true
  - type: input
    id: qq-id
    attributes:
      label: QQ号
      description: 您的QQ号。
      placeholder: e.g. 10000
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 介绍一下你自己
      description: 你还想告诉我们什么？
      placeholder: 什么都可以哦，没有就算了吧。
    validations:
      required: false
